### ISSUE TITLE
Empty Response with Status does not send a status

### ISSUE THREAD

**Issue by zombiesplat** [equip/framework#34]
To reproduce: 
From any Domain class::__invoke `return $this->payload->withStatus(PayloadInterface::STATUS_NOT_FOUND);`

return this and the header data will say 200 OK; if I add a `->withOutput('anything');` I will get the proper status header. 404

I have tracked this down to src/Responder/FormattedResponder.php::53 `if ($this->hasOutput($payload) {` 

It seems like that is there for a reason, and I was going to make some edits and submit a pull request but I'm struggling to get the test environment set up for tonight. So I'll submit an issue instead.

**Comment by shadowhand** [comment]
Ah yes, this is a bit convoluted and really a case of bad separation of concerns. The `AbstractFormatter` converts legacy status codes into HTTP codes. Really the formatters don't need to be concerned with status code at all.

I'm wary of modifying too much of this before 2.0, since fixing it properly will require changing some of the execution flow. This also relates to equip/adr#5.

**Comment by zombiesplat** [comment]
Okay, I can live with that. I'll just throw an HTTP Exception or pass data back with my response for now.

**Comment by shadowhand** [comment]
Reopening... we have a `dev` branch that contains 2.0 fixes. We'll address this there.

**Comment by shadowhand** [comment]
This has been committed to `dev` and will be resolved in version 2.0.
